import os
import pygame

WIDTH, HEIGHT = 900, 500

WHITE_COLOR = (255, 255, 255)
BLACK_COLOR = (0, 0, 0)

FPS = 60
VELOCITY = 5
BULLET_VELOCITY = 7
MAX_BULLETS = 3

YELLOW_SPACESHIP_LOCATION = (300, 100)
RED_SPACESHIP_LOCATION = (700, 100)
YELLOW_SPACESHIP_RESIZE_SIZE = (55, 40)
RED_SPACESHIP_RESIZE_SIZE = (55, 40)

RED_SPACESHIP_X, RED_SPACESHIP_Y = 700, 300
YELLOW_SPACESHIP_X, YELLOW_SPACESHIP_Y = 100, 300

IMAGE_ROTATE_ANGLE = 90
IMAGE_ROTATE_ANGLE_OTHER_WAY = 270
BORDER_RECT_OFFSET = 5

BORDER = pygame.Rect(WIDTH / 2 - BORDER_RECT_OFFSET, 0, 10, HEIGHT)

YELLOW_SPACESHIP_IMAGE = pygame.image.load(os.path.join("assets", "spaceship_yellow.png"))
YELLOW_SPACESHIP = pygame.transform.rotate(
    pygame.transform.scale(YELLOW_SPACESHIP_IMAGE, YELLOW_SPACESHIP_RESIZE_SIZE), IMAGE_ROTATE_ANGLE)
RED_SPACESHIP_IMAGE = pygame.image.load(os.path.join("assets", "spaceship_red.png"))
RED_SPACESHIP = pygame.transform.rotate(
    pygame.transform.scale(RED_SPACESHIP_IMAGE, RED_SPACESHIP_RESIZE_SIZE), IMAGE_ROTATE_ANGLE_OTHER_WAY)